# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171008_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='expertise',
        ),
        migrations.AddField(
            model_name='user',
            name='expertise',
            field=models.ManyToManyField(to='main.UserExpertise'),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='post',
            field=models.TextField(max_length=140),
        ),
    ]
