# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20171008_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfriend',
            name='date',
            field=models.DateTimeField(default='2017-10-6 06:00:00+0700'),
            preserve_default=False,
        ),
    ]
