# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20171012_1157'),
        ('main', '0008_auto_20171011_2204'),
    ]

    operations = [
    ]
